aws_region = "us-east-1"
database_name = "db1"
database_storage = [10, 50]
database_instance =  ["db.t3.micro","db.t3.small"]
sec_group_ids = ["sg-27af4c74"]
subnet_id = "subnet-54417e33"
ec2_instance = ["t2.micro","t2.small","t2.medium"]
bucket_name = "bucket-s3-with-html-files-to-deploy-001100"
resource_or_module_bucket = "module"